name: 🐞 Bug
description: File a bug/issue
title: "bug: <title>"
labels: [S-unverified, C-bug, P-medium]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      placeholder: Tell us what you expected to see!
    validations:
      required: true
  - type: dropdown
    id: track
    attributes:
      label: Version
      description: What version are you running?
      options:
        - Stable
        - Canary
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: System Info & Logs
      description: Please include the latest logs from the logs folder, no need to include backticks your logs will be automatically formatted
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true