name: 💡 Feature
description: Suggest a new feature
title: "feat: <title>"
labels: [S-unverified, C-feature, P-low]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: new-feature-details
    attributes:
      label: What is your new suggestion? Please include all details.
      placeholder: Tell us what you expected to see!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Anything else?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true