name: Builds
on:
  push:
    branches:
      - stable
      - canary
  pull_request:
    branches:
      - stable
      - canary
jobs:
  Build-Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Tauri Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: Install Node.js Dependencies
        run: yarn
      - name: Build
        run: yarn web:build