name: Production
on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable
jobs:
  Publish-Stable-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🤖 Automatic Builds aren't ready yet!"
      # TODO (HarryET): Auto push new stable build to application