name: Tests
on: [push, pull_request]
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install`
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:run # will run `yarn test:run`